server:
  port: 8098

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/polling_app?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: TEst.2020
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: CST

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

app:
  jwtSecret: 9a02115a835ee03d5fb83cd8a468ea33e4090aaaec87f53c9fa54512bbef4db8dc656c82a315fa0c785c08b0134716b81ddcd0153d2a7556f2e154912cf5675f
  jwtExpirationInMs: 604800000
  cors:
    allowedOrigins: http://localhost:8098
